# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'BSBDJDemo' do

pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJExtension"
pod "MJRefresh"

end
